# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# -   repo: https://github.com/psf/black
#     rev: 22.3.0
#     hooks:
#     -   id: black
#         language_version: python3

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      -   id: prettier
          files: '.*\.(ts)'
          args: ['--parser', 'typescript', '--write']
      -   id: prettier
          files: '.*\.(scss)'
          args: ['--parser', 'scss', '--write']
      -   id: prettier
          files: '.*\.(html)'
          args: ['--parser', 'html', '--write']

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.42.0
    hooks:
      - id: eslint
