services:
    rasp-water:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        stdin_open: true
        volumes:
            - ./flask/data:/opt/rasp-water/flask/data
            - ./config.example.yaml:/opt/rasp-water/config.yaml:ro
        ports:
            - "5000:5000"

        privileged: true
        devices:
            - "/dev/gpiomem:/dev/gpiomem"
            - "/sys/bus/iio/devices/iio:device0:/sys/bus/iio/devices/iio:device0"
