// Build information, automatically generated by `ng-info`
const build = {
    version: '0.0.0',
    timestamp: 'Mon Apr 28 2025 22:47:05 GMT+0900 (日本標準時)',
    message: null,
    git: {
        user: 'KIMATA Tetsuya',
        branch: 'master',
        hash: '4a220c',
        fullHash: '4a220c72b67c104ff6664e3781c1be393dabc020',
    },
};

export default build;
